In [1]:
import pandas as pd

In [3]:
#read cvs
df = pd.read_csv(r'C:\Users\ACER\Downloads\financial_loan.csv')
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [6]:
df['issue_date'] = pd.to_datetime(df['issue_date'], dayfirst=True, format ='mixed')

In [ ]:
df['month'] = df['issue_date'].dt.month_name()

In [12]:
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,month
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,13-09-2021,13-04-2021,...,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009,February
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,14-12-2021,15-01-2021,...,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939,January
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,12-12-2021,09-01-2021,...,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522,January
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,12-12-2021,12-03-2021,...,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911,February
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,14-12-2021,15-01-2021,...,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835,January

In [10]:
result = df.groupby('month').size().reset_index(name='count').sort_values('month')
print(result)

        month  count
0       April   2755
1      August   3441
2    December   4314
3    February   2279
4     January   2332
5        July   3366
6        June   3184
7       March   2627
8         May   2911
9    November   4035
10    October   3796
11  September   3536

In [11]:
df.to_csv('financial_loan_clean.csv')